# Generated by Django 5.0.6 on 2024-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversations",
            name="genre",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="conversations",
            name="keywords",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="conversations",
            name="style",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="conversations",
            name="themes",
            field=models.CharField(),
        ),
    ]
